 version: 2.1
 jobs:
      build:
        docker:
          - image: cimg/base:2022.06
            auth:
              username: $DOCKERHUB_USERNAME
              password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        steps:
          - setup_remote_docker:
              version: 20.10.14
              docker_layer_caching: true
          - checkout
          - run: pwd
          - run: |
                  docker-compose -f docker-compose-build.yaml build --parallel
                  
                  docker tag udagram-api-user ${DOCKERHUB_USERNAME}/udagram-api-user
                  docker tag udagram-api-feed ${DOCKERHUB_USERNAME}/udagram-api-feed
                  docker tag udagram-frontend:local ${DOCKERHUB_USERNAME}/udagram-frontend
                  docker tag reverseproxy ${DOCKERHUB_USERNAME}/udagram-reverseproxy

                  echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                  docker push ${DOCKERHUB_USERNAME}/udagram-api-user
                  docker push ${DOCKERHUB_USERNAME}/udagram-api-feed
                  docker push ${DOCKERHUB_USERNAME}/udagram-frontend
                  docker push ${DOCKERHUB_USERNAME}/udagram-reverseproxy
  



# version: 2.1

# orbs:
#   node: circleci/node@4.7

# workflows:
#   build:
#     jobs:
#       - build:
#           context: udagram

# jobs:
#   build:
#     docker:
#       - image: cimg/node:14.15.5
#         auth:
#          username: $DOCKERHUB_USERNAME
#          password: $DOCKERHUB_PASSWORD
#     steps:
#       - checkout
#       - setup_remote_docker:
#           version: 20.10.14
#           docker_layer_caching: true
#       - run:
#           name: Build, Tag and Push Docker images to Docker Hub
#           command: |
#             docker-compose -f docker-compose-build.yaml build --parallel
#             docker tag udagram-api-feed kehindeafusat/udagram-api-feed
#             docker tag udagram-api-user kehindeafusat/udagram-api-user
#             docker tag udagram-frontend kehindeafusat/udagram-frontend:local
#             docker tag udagram-reverseproxy kehindeafusat/udagram-reverseproxy
#             echo $DOCKER_PASSWORD | docker login -u kehindeafusat --password-stdin
#             docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            
#             docker push kehindeafusat/udagram-api-feed
#             docker push kehindeafusat/udagram-api-user
#             docker push kehindeafusat/udagram-frontend:local
#             docker push kehindeafusat/udagram-reverseproxy