version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  build:
    jobs:
      - build:
          context: udagram

jobs:
  build:
    docker:
      - image: cimg/node:14.15.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build, Tag and Push Docker images to Docker Hub
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag udagram-api-feed kehindeafusat/udagram-api-feed:v4a
            docker tag udagram-api-user kehindeafusat/udagram-api-user:v4a
            docker tag udagram-frontend kehindeafusat/udagram-frontend:local
            docker tag udagram-reverseproxy kehindeafusat/udagram-reverseproxy:v5a
            echo $DOCKER_PASSWORD | docker login -u kehindeafusat --password-stdin
            docker push kehindeafusat/udagram-api-feed:v4a
            docker push kehindeafusat/udagram-api-user:v4a
            docker push kehindeafusat/udagram-frontend:local
            docker push kehindeafusat/udagram-reverseproxy:v5a