apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagam-reverseproxy
spec:
  type: ClusterIP
  selector:
    app: udagram-reverseproxy
  ports:
  - protocol: TCP
    name: "8080"
    port: 8080
    targetPort: 8080